// Runs actual embedded JS with a minimal DOM; never talks to real hardware.
const vm=require('node:vm'),fs=require('node:fs'),assert=require('node:assert/strict');
const html=fs.readFileSync(__dirname+'/../web/index.html','utf8'),script=html.match(/<script>([\s\S]*)<\/script>/)[1].replace(/\(async function poll\(\)\{[\s\S]*$/, '');
const elements=new Map();function el(id){if(!elements.has(id))elements.set(id,{value:'',textContent:'',disabled:false,files:[],dataset:{},classList:{toggle(){}},setAttribute(){},showModal(){},close(){},replaceChildren(){},append(){}});return elements.get(id)}
const buttons=[el('#power'),...Array.from({length:3},(_,i)=>el('#mode'+i))];buttons.forEach((b,i)=>b.dataset={action:i?'mode':'power',value:String(i?i-1:1)});
let data={token:'test',connected:true,configReady:true,controlReady:true,commandId:0,state:{power:1,mode:0,cadr:36,water:70,humidity:5500,temperature:2900,hThreshold:50,lock:0,waterflood:0},controlDiagnostic:{savedConfig:{CADR:37}},network:{canConfigure:true}};
const calls=[];let failArm=false;const ctx=vm.createContext({document:{createElement:()=>({}),querySelector:el,querySelectorAll:()=>buttons,body:{classList:{toggle(){}}}},fetch:async(path,options)=>{calls.push(path);return{ok:!(failArm&&path==='/api/arm'),json:async()=>path==='/api/status'?data:failArm&&path==='/api/arm'?{error:'rejected'}:{sent:true}}},AbortSignal,TextEncoder,Date,console,Error,setTimeout});vm.runInContext(script,ctx);ctx.fixture=data;
(async()=>{
 vm.runInContext('render(fixture)',ctx);assert.equal(el('#airflow').value,37);assert.equal(el('#airflow').disabled,false);
 data.goose={online:true,temperature:3080,humidity:5400,ageMs:1000,boundMac:'58:2d:34:10:06:b1',candidates:[{mac:'58:2d:34:10:06:b1',temperature:3080,humidity:5400}]};vm.runInContext('render(fixture)',ctx);assert.equal(el('#humidity').textContent,'54.0');assert.equal(el('#temperature').textContent,'30.8');assert.equal(el('#readingSource').textContent,'外置湿度 · CGG1');data.goose.selectedSource='internal';vm.runInContext('render(fixture)',ctx);assert.equal(el('#humidity').textContent,'55.0');assert(el('#externalReading').textContent.includes('54.0%'));assert(el('#internalReading').textContent.includes('55.0%'));data.goose.selectedSource='external';data.goose.online=false;vm.runInContext('render(fixture)',ctx);assert.equal(el('#humidity').textContent,'55.0');assert.equal(el('#readingSource').textContent,'机内湿度');
 data.state.mode=1;vm.runInContext('render(fixture)',ctx);assert.equal(el('#targetSlider').disabled,false);data.state.mode=0;vm.runInContext('render(fixture)',ctx);assert.equal(el('#targetSlider').disabled,true);data.pending=true;vm.runInContext('render(fixture)',ctx);assert.equal(el('#message').textContent,'正在执行，请稍候…');data.pending=false;vm.runInContext('render(fixture)',ctx);assert.notEqual(el('#message').textContent,'正在执行，请稍候…');
 data.health={pump:'start_reported',waterUsage:{infinite:false,hours:4.5,reason:'estimate',samples:4}};data.diagnosticsEnabled=false;vm.runInContext('render(fixture)',ctx);assert.equal(el('#waterHours').textContent,'4.5 小时');assert.equal(el('#diagnostic').hidden,true);data.health.waterUsage={infinite:true,hours:null,reason:'no_drop'};vm.runInContext('render(fixture)',ctx);assert.equal(el('#waterHours').textContent,'∞');
 data.state.waterflood=1;vm.runInContext('render(fixture)',ctx);assert.equal(el('#airflow').disabled,true);assert.equal(buttons[1].disabled,true);assert.equal(buttons[0].disabled,false);
 data.state.waterflood=0;data.state.mode=5;vm.runInContext('render(fixture)',ctx);assert.equal(el('#airflow').disabled,true);
 data.state.mode=0;data.connected=false;vm.runInContext('render(fixture)',ctx);assert(buttons.every(b=>b.disabled));
 data.connected=true;vm.runInContext('render(fixture)',ctx);calls.length=0;
 const first=vm.runInContext("control({action:'airflow',value:37})",ctx);await vm.runInContext("control({action:'power',value:0})",ctx);await first;assert.deepEqual(calls,['/api/arm','/api/control','/api/status']);
 failArm=true;calls.length=0;await vm.runInContext("control({action:'power',value:0})",ctx);assert.deepEqual(calls,['/api/arm','/api/status']);
 assert(!html.includes('data-action="refill"'));assert(!html.includes('id="arm"'));console.log('PASS: saved airflow sync, refill/protected/offline guards, sequential arm/control, double-click exclusion, failed arm sends no control, physical-only refill');
})().catch(e=>{console.error(e);process.exit(1)});
